### ISSUE TITLE
musl-libc compatibility

### ISSUE THREAD

**Issue by kit-ty-kate** [janestreet/core_unix#15]
The latest version of core_unix (v0.17.0) fails on Alpine Linux with (amongst other error messages):
```
linux_ext_stubs.c: In function 'core_linux_sendmsg_nonblocking_no_sigpipe_stub':
linux_ext_stubs.c:239:45: error: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  239 |   struct msghdr msghdr = {NULL, 0, NULL, 0, NULL, 0, 0};
      |                                             ^~~~
linux_ext_stubs.c:239:45: note: (near initialization for 'msghdr.__pad1')
```

**Comment by copy** [comment]
Fix in  #12

**Comment by dkalinichenko-js** [comment]
Should be resolved in master.

**Comment by kit-ty-kate** [comment]
do you have a rough idea when should the next major release be?

**Comment by dkalinichenko-js** [comment]
Scheduled for March this year, probably soon after we upgrade to 5.4.
